version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "Composer"
      include: "scope"
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "npm"
    directory: "/web/themes/custom/contribtracker/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github-actions"
