version: "3.6"

services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:6
    ports:
      - 6379
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
    volumes:
      - ".:/mnt/ddev_config"
      - "./redis:/usr/local/etc/redis"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks: [default, ddev_default]
  web:
    depends_on:
      - redis
    links:
      - redis:redis
